### PR TITLE
Add unit tests for issue #44.

### PR DESCRIPTION
**Pull request by ghost**
Add unit tests for issue #44.
The target classes are listed below.
- ODataSvcCollectionResource
- ODataSvcSchemaResource

### CODE REVIEW

**Comment by SawamiWataru** [comment]
Thank you for creating the test.

Describe the results of the review.
Sorry to trouble you, but please fix it.

### AllTests
- The line feed code is CR + LF. Please correct to LF.
  (Although we are not currently able to maintain it, Personium's line feed code is supposed to be unified with LF)

### ODataSvcCollectionResourceTest
- @RunWith, @PrepareForTest is unnecessary.
- Deleting the annotation makes it unnecessary for the following imports.
  - import org.junit.runner.RunWith;
  - import org.powermock.api.mockito.PowerMockito;
  - import org.powermock.core.classloader.annotations.PrepareForTest;
  - import org.powermock.modules.junit4.PowerMockRunner;
- @SuppressWarnings is unnecessary.
- [throws Exception] is unnecessary.
- The method name is preferably constructor_Normal.

### ODataSvcSchemaResource
- [import org.powermock.api.mockito.PowerMockito;] is unnecessary.
- It is unnecessary to specify ODataSvcSchemaResource.class in @PrepareForTest.
- @SuppressWarnings is unnecessary.
- [throws Exception] is unnecessary.
- The method name is preferably constructor_Normal.

#### Supplement for method name
We are in the middle of maintenance, but PT method names will be unified below.
   - Normal scenarios: foo_Normal_ {summary}
   - Error scenarios: bar_Error_ {summary}
If the pattern is single, {summary} is unnecessary.

I think that the following source code will be helpful.
https://github.com/personium/personium-core/blob/master/src/test/java/io/personium/core/model/impl/fs/DavMetadataFileTest.java

**Comment by SawamiWataru** [comment]
Thank you for creating the test.

Describe the results of the review.
Sorry to trouble you, but please fix it.

### AllTests
- The line feed code is CR + LF. Please correct to LF.
  (Although we are not currently able to maintain it, Personium's line feed code is supposed to be unified with LF)

### ODataSvcCollectionResourceTest
- @RunWith, @PrepareForTest is unnecessary.
- Deleting the annotation makes it unnecessary for the following imports.
  - import org.junit.runner.RunWith;
  - import org.powermock.api.mockito.PowerMockito;
  - import org.powermock.core.classloader.annotations.PrepareForTest;
  - import org.powermock.modules.junit4.PowerMockRunner;
- @SuppressWarnings is unnecessary.
- [throws Exception] is unnecessary.
- The method name is preferably constructor_Normal.

### ODataSvcSchemaResource
- [import org.powermock.api.mockito.PowerMockito;] is unnecessary.
- It is unnecessary to specify ODataSvcSchemaResource.class in @PrepareForTest.
- @SuppressWarnings is unnecessary.
- [throws Exception] is unnecessary.
- The method name is preferably constructor_Normal.

#### Supplement for method name
We are in the middle of maintenance, but PT method names will be unified below.
   - Normal scenarios: foo_Normal_ {summary}
   - Error scenarios: bar_Error_ {summary}
If the pattern is single, {summary} is unnecessary.

I think that the following source code will be helpful.
https://github.com/personium/personium-core/blob/master/src/test/java/io/personium/core/model/impl/fs/DavMetadataFileTest.java

**Comment by nisiguti** [comment]
Thank you for reviewing the test codes.
I correct the places that were pointed out.

**Comment by SawamiWataru** [comment]
Thank you for fixing.
I will approve PullRequest as there is no problem.

**Pull request merged**
