### PR TITLE
Fix crossdomain xml

### LINKED ISSUE #444: crossdomain.xml error in Eclipse
err

This error cause is the referenced URL is "Moved 301 Permanently".

### PR DESCRIPTION
**Pull request by tochi-y**
Fix #444

### CODE REVIEW

**Comment by personiumio** [comment]
Can one of the admins verify this patch?

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Comment by tochi-y** [comment]
ok to test

**Pull request merged**
